info:
  experiment: "{{cookiecutter.experiment_name}}" # compulsory
  subject: "" # compulsory
  session: "" # compulsory
  run: "" # compulsory
  task_name: "" # compulsory
  modality: "beh" # beh | mri | eeg | meg

settings:
  debug: false
  window_size: "full_screen" # [800, 600]
  mouse_visible: false
  logging_level: "INFO"
  font_size: 12

keys: ["1", "2", "3", "4"]

# MRI related settings
fmri_setting:
  trigger: "t"
  dummy_vol: 3
  tr: 3
  slice_per_vol: 60

instructions:
  exp_txt: "./instructions/instruction.txt"
  end_txt: "./instructions/end_instr.txt"

trials_file: "./stimuli/trials.csv"
